services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - elasticsearch
    volumes:
      - ./src:/app/src

networks:
  app-network:
    driver: bridge
