services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=mydatabase # Optional: Specify the database name
    container_name: mysql
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - '3306:3306'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ./src:/app/src

networks:
  app-network:
    driver: bridge
  elasticsearch:
    driver: bridge
